baseURL = "https://deelu96.github.io/webApp/"
languageCode = "en-us"
title = "AutoGeekPro"
theme = "ananke"
disqusShortname = "AutoGeek"
publishDir = "docs"

[params]
  commentoEnable = false
  body_classes = "athelas bg-white"
  background_color_class = "light-gray { color: #EEEEEE } bg-dark-red { background-color: #E7040F }"

